### ISSUE TITLE
Damage Numbers cause a null ref exception when the player dies

### ISSUE THREAD

**Issue by Lafolie** [Lafolie/Final-Minecraft#23]
```
java.lang.NullPointerException: Cannot invoke "lafolie.fmc.core.entity.DamageNumbers.spawnDamageNumbers(net.minecraft.client.MinecraftClient, float, lafolie.fmc.core.internal.network.HealthModifiedPacket$EventType)" because "dmgEntity" is null
	at lafolie.fmc.core.FinalMinecraftClient.lambda$registerNetworkReceivers$1(FinalMinecraftClient.java:65) ~[main/:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:157) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:131) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:116) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1085) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:737) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
[00:06:23] [Render thread/ERROR] (Minecraft) Error executing task on Client
java.lang.NullPointerException: Cannot invoke "lafolie.fmc.core.entity.DamageNumbers.spawnDamageNumbers(net.minecraft.client.MinecraftClient, float, lafolie.fmc.core.internal.network.HealthModifiedPacket$EventType)" because "dmgEntity" is null
	at lafolie.fmc.core.FinalMinecraftClient.lambda$registerNetworkReceivers$1(FinalMinecraftClient.java:65) ~[main/:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:157) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:131) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:116) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1085) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:737) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
[00:06:25] [Render thread/ERROR] (Minecraft) Error executing task on Client
java.lang.NullPointerException: Cannot invoke "lafolie.fmc.core.entity.DamageNumbers.spawnDamageNumbers(net.minecraft.client.MinecraftClient, float, lafolie.fmc.core.internal.network.HealthModifiedPacket$EventType)" because "dmgEntity" is null
	at lafolie.fmc.core.FinalMinecraftClient.lambda$registerNetworkReceivers$1(FinalMinecraftClient.java:65) ~[main/:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:157) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:131) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:116) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1085) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:737) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
	```

**Comment by Lafolie** [comment]
This has been fixed.
